/*
 * customer.java
 *
 * Created on May 12, 2017, 10:28 PM
 */
package ordermanagementsystem;

import com.jtattoo.plaf.mcwin.McWinLookAndFeel;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;
import java.awt.Image;
import java.io.File;
import java.util.HashMap;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author  Rakshitha Kasun
 */
public class customer extends javax.swing.JFrame {

    /** Creates new form customer */
    public customer() {
        initComponents();
        txtid.setText("");
        txtname.setText("");
        txtadd.setText("");
        txttele.setText("");
        txtemail.setText("");
        txtnic.setText("");
        cmbtype.setSelectedIndex(0);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        lblimg = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        JBhome = new javax.swing.JButton();
        txtnic = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        txtadd = new javax.swing.JTextField();
        txttele = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        cmbtype = new javax.swing.JComboBox();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel1.setText("NIC"); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 180, 50));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel2.setText("CUSTOMER ID"); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 180, 50));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel3.setText("CUSTOMER NAME"); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 250, 50));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel4.setText("ADDRESS"); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 180, 50));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel5.setText("TELEPHONE"); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 180, 50));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel6.setText("EMAIL"); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 180, 50));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("UPLOAD IMAGE"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 170, 30));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("SAVE"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, 130, 30));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("SEARCH"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 500, 130, 30));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("UPDATE"); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 500, 130, 30));

        lblimg.setBackground(new java.awt.Color(51, 255, 255));
        lblimg.setBorder(javax.swing.BorderFactory.createTitledBorder("IMAGE"));
        getContentPane().add(lblimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 260, 160));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setText("DELETE"); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 500, 130, 30));

        JBhome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JBhome.setText("LOGOUT"); // NOI18N
        JBhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBhomeActionPerformed(evt);
            }
        });
        getContentPane().add(JBhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 50, 130, 20));

        txtnic.setText("jTextField1"); // NOI18N
        txtnic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnicActionPerformed(evt);
            }
        });
        getContentPane().add(txtnic, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, 210, 40));

        txtid.setText("jTextField1"); // NOI18N
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 210, 40));

        txtname.setText("jTextField1"); // NOI18N
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        getContentPane().add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 210, 40));

        txtadd.setText("jTextField1"); // NOI18N
        txtadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaddActionPerformed(evt);
            }
        });
        getContentPane().add(txtadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 210, 40));

        txttele.setText("jTextField1"); // NOI18N
        txttele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtteleActionPerformed(evt);
            }
        });
        getContentPane().add(txttele, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 210, 40));

        txtemail.setText("jTextField1"); // NOI18N
        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        getContentPane().add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 210, 40));

        cmbtype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECT CUSTOMER TYPE", "WHOLE SALE", "RETAIL SALE" }));
        getContentPane().add(cmbtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, 200, -1));

        jButton6.setText("Back");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 550, 130, 20));

        jButton7.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jButton7.setText("GENERATE FULL REPORT"); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 400, 220, -1));

        jButton8.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jButton8.setText("GENERATE CUSTOMER REPORT"); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 440, 220, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel7.setText("CUSTOMER DETAILS"); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 460, 30));

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel10.setText("CUSTOMER TYPE"); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 220, 50));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/solid_colors_stains_light_18571_1920x1200.jpg"))); // NOI18N
        jLabel8.setText("jLabel8"); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 790, 680));

        setSize(new java.awt.Dimension(788, 635));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    try {
        jFileChooser1.showOpenDialog(this);
        File f = jFileChooser1.getSelectedFile();
        String path = f.getAbsolutePath();
        path = path.replace("\\", "/");
        File f1 = new File(path);

        Image im = ImageIO.read(f1);
        im = im.getScaledInstance(lblimg.getWidth(), lblimg.getHeight(), Image.SCALE_SMOOTH);
        lblimg.setIcon(new ImageIcon(im));






    } catch (Exception e) {
        e.printStackTrace();
    }

}//GEN-LAST:event_jButton1ActionPerformed

private void JBhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBhomeActionPerformed
// TODO add your handling code here:
    new loging().setVisible(true);
    this.dispose();
}//GEN-LAST:event_JBhomeActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
    try {
        File f = jFileChooser1.getSelectedFile();
        String path = f.getAbsolutePath();
        path = path.replace("\\", "/");

        int x = JOptionPane.showConfirmDialog(rootPane, "Do you want to save?");
        if (x == 0) {
            Connection c = DB.mycon();
            Statement s = c.createStatement();
            validation v = new validation();
           
            if(v.isValidName(txtname.getText())== !false && v.isValidPhoneNumber(txttele.getText())==!false && v.isValidEmail(txtemail.getText())== !false && v.isValidID(txtnic.getText())== !false){
            s.executeUpdate("INSERT INTO customer VALUES ('" + txtid.getText() + "','" + txtname.getText() + "','" + txtadd.getText() + "','" + txttele.getText() + "','" + txtemail.getText() + "','" + txtnic.getText() + "','" + cmbtype.getSelectedItem().toString() + "','" + path + "')");
            txtid.setText("");
            txtname.setText("");
            txtadd.setText("");
            txttele.setText("");
            txtemail.setText("");
            txtnic.setText("");
            cmbtype.setSelectedIndex(0);
            lblimg.setIcon(null);
            JOptionPane.showMessageDialog(rootPane, "Successfully Saved");
        } else if (x == 1) {
            txtid.setText("");
            txtname.setText("");
            txtadd.setText("");
            txttele.setText("");
            txtemail.setText("");
            txtnic.setText("");
            cmbtype.setSelectedIndex(0);
            lblimg.setIcon(null);
        }

    } }catch (Exception e) {
        e.printStackTrace();
    }


}//GEN-LAST:event_jButton2ActionPerformed

private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
// TODO add your handling code here:
    txtname.grabFocus();
}//GEN-LAST:event_txtidActionPerformed

private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
// TODO add your handling code here:
    txtadd.grabFocus();
}//GEN-LAST:event_txtnameActionPerformed

private void txtaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaddActionPerformed
// TODO add your handling code here:
    txttele.grabFocus();
}//GEN-LAST:event_txtaddActionPerformed

private void txtteleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtteleActionPerformed
// TODO add your handling code here:
    txtemail.grabFocus();
}//GEN-LAST:event_txtteleActionPerformed

private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
// TODO add your handling code here:
    txtnic.grabFocus();
}//GEN-LAST:event_txtemailActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
// TODO add your handling code here:
    try {
        Connection c = DB.mycon();
        Statement s = c.createStatement();
        ResultSet rs = s.executeQuery("SELECT * FROM customer WHERE id='" + txtid.getText() + "'");
        while (rs.next()) {
            txtname.setText(rs.getString("name"));
            txtadd.setText(rs.getString("address"));
            txttele.setText(rs.getString("telephone"));
            txtemail.setText(rs.getString("email"));
            txtnic.setText(rs.getString("nic"));
            cmbtype.setSelectedItem(rs.getString("type"));

            File f1 = new File(rs.getString("image"));

            Image im = ImageIO.read(f1);
            im = im.getScaledInstance(lblimg.getWidth(), lblimg.getHeight(), Image.SCALE_SMOOTH);
            lblimg.setIcon(new ImageIcon(im));

        }

    } catch (Exception e) {
        e.printStackTrace();
    }
}//GEN-LAST:event_jButton3ActionPerformed

private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
// TODO add your handling code here:
    int x = JOptionPane.showConfirmDialog(rootPane, "Do you want to Update?");
    if (x == 0) {
        try {
            Connection c = DB.mycon();
            Statement s = c.createStatement();
              validation v = new validation();
            s.executeUpdate("UPDATE customer SET name= '" +txtname.getText() + "',address='" + txtadd.getText() + "',telephone='" + txttele.getText() + "',email='" + txtemail.getText() + "',nic='" + txtnic.getText() + "',type='" + cmbtype.getSelectedItem().toString() + "'WHERE id='" + txtid.getText() + "'");

            txtid.setText("");
            txtname.setText("");
            txtadd.setText("");
            txttele.setText("");
            txtemail.setText("");
            txtnic.setText("");
            cmbtype.setSelectedIndex(0);
            lblimg.setIcon(null);
            JOptionPane.showMessageDialog(rootPane, "Successfully updated");
            

        } catch (Exception e) {
            e.printStackTrace();
        }

    } else if (x == 1) {
        txtid.setText("");
        txtname.setText("");
        txtadd.setText("");
        txttele.setText("");
        txtemail.setText("");
        txtnic.setText("");
        cmbtype.setSelectedIndex(0);
        lblimg.setIcon(null);
    }
}//GEN-LAST:event_jButton4ActionPerformed

private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
// TODO add your handling code here:
    int x = JOptionPane.showConfirmDialog(rootPane, "Do you want to Delete?");
    if (x == 0) {
        try {
          
            Connection c = DB.mycon();
            Statement s = c.createStatement();
            s.executeUpdate("DELETE from customer WHERE id='" + txtid.getText() + "'");
            txtid.setText("");
            txtname.setText("");
            txtadd.setText("");
            txttele.setText("");
            txtemail.setText("");
            txtnic.setText("");
            cmbtype.setSelectedIndex(0);
            lblimg.setIcon(null);

            JOptionPane.showMessageDialog(rootPane, "Deleted Succesfuly");

        } catch (Exception e) {
            e.printStackTrace();
        }
    } else if (x == 1) {
        txtid.setText("");
        txtname.setText("");
        txtadd.setText("");
        txttele.setText("");
        txtemail.setText("");
        txtnic.setText("");
        cmbtype.setSelectedIndex(0);
        lblimg.setIcon(null);
    }
}//GEN-LAST:event_jButton5ActionPerformed

private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
// TODO add your handling code here:
    try {
        /* A sample calling */
        HashMap param = new HashMap();
//param.put("reportParameterName",valueForTheParameter);
        MyiReportViewer viewer = new MyiReportViewer("C:\\Users\\Rakshitha Kasun\\Desktop\\ST2PROJECT\\ireport\\customers.jasper", param);
        viewer.setVisible(true);

    } catch (Exception e) {
        e.printStackTrace();
    }
}//GEN-LAST:event_jButton7ActionPerformed

private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
// TODO add your handling code here:
    try {
        /* A sample calling */
        HashMap param = new HashMap();
        param.put("cat", txtid.getText());
        MyiReportViewer viewer = new MyiReportViewer("C:\\Users\\Rakshitha Kasun\\Desktop\\ST2PROJECT\\ireport\\customerdetails.jasper", param);
        viewer.setVisible(true);

    } catch (Exception e) {
        e.printStackTrace();
    }
}//GEN-LAST:event_jButton8ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        home h=new home();
        h.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txtnicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnicActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {

                try {
                    UIManager.setLookAndFeel(new McWinLookAndFeel());

                } catch (Exception e) {
                    e.printStackTrace();
                }
                new customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBhome;
    private javax.swing.JComboBox cmbtype;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblimg;
    private javax.swing.JTextField txtadd;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtnic;
    private javax.swing.JTextField txttele;
    // End of variables declaration//GEN-END:variables
}
