/*
 * loging.java
 *
 * Created on May 11, 2017, 11:51 PM
 */
package ordermanagementsystem;

import com.jtattoo.plaf.mcwin.McWinLookAndFeel;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.UIManager;

/**
 *
 * @author  Rakshitha Kasun
 */
public class loging extends javax.swing.JFrame {

    /** Creates new form loging */
    public loging() {
        initComponents();
        txtpasswort.setText("");
        txtusername.setText("");
        lblerrror.setVisible(false);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtpasswort = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        lblerrror = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("USER NAME   :"); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 300, 70));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PASSWORD    :"); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        txtusername.setText("jTextField1"); // NOI18N
        txtusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernameActionPerformed(evt);
            }
        });
        getContentPane().add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 260, 40));

        jButton1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jButton1.setText("Reset"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 300, 170, 30));

        jButton2.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jButton2.setText("LOGIN"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 170, 30));

        txtpasswort.setText("jPasswordField1"); // NOI18N
        getContentPane().add(txtpasswort, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 260, 40));

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 130, 30));

        lblerrror.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblerrror.setForeground(new java.awt.Color(255, 0, 0));
        lblerrror.setText("INCORRECT"); // NOI18N
        getContentPane().add(lblerrror, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 230, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ORDER MANAGEMENT SYSTEM"); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 560, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IMG_89095.jpg"))); // NOI18N
        jLabel5.setText("jLabel5"); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 460));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/adp-bg-background01-opt.jpg"))); // NOI18N
        jLabel3.setText("jLabel3"); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 920, 380));

        setSize(new java.awt.Dimension(890, 406));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    txtusername.setText("");
    txtpasswort.setText("");
    lblerrror.setVisible(false);
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:



    try {

        Connection c = DB.mycon();
        Statement s = c.createStatement();
        ResultSet rs = s.executeQuery("SELECT * FROM loginorder");

        String password = txtpasswort.getText();
        String username = txtusername.getText();

        while (rs.next()) {
            if (username.equals(rs.getString("username")) && password.equals(rs.getString("password"))) {
                
                if (rs.getString("type").equals("hrmmanager")) {
                    new employee().setVisible(true);
                    this.dispose();
                    break;
                } else if (rs.getString("type").equals("customermanager")) {
                    new customer().setVisible(true);
                    this.dispose();
                    break;
                } else if (rs.getString("type").equals("suppliermanager")) {
                    new supplier().setVisible(true);
                    this.dispose();
                    break;
                } else if (rs.getString("type").equals("productmanager")) {
                    new product().setVisible(true);
                    this.dispose();
                    break;
                } else if (rs.getString("type").equals("cashier")) {
                    new poss().setVisible(true);
                    this.dispose();
                    break;
                }
            } else {
                lblerrror.setVisible(true);
                txtusername.setText("");
                txtpasswort.setText("");
            }
        }

    } catch (Exception e) {
        e.printStackTrace();
    }
}//GEN-LAST:event_jButton2ActionPerformed

private void txtusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernameActionPerformed
// TODO add your handling code here:
    txtpasswort.grabFocus();
}//GEN-LAST:event_txtusernameActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new home().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {

                try {
                    UIManager.setLookAndFeel(new McWinLookAndFeel());

                } catch (Exception e) {
                    e.printStackTrace();
                }
                new loging().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblerrror;
    private javax.swing.JPasswordField txtpasswort;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
