/*
 * pos.java
 *
 * Created on January 1, 2017, 11:03 AM
 */
package ordermanagementsystem;

import com.jtattoo.plaf.mcwin.McWinLookAndFeel;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author  DON
 */
public class poss extends javax.swing.JFrame {

    double subtot = 0;
    double grandtot = 0;

    /** Creates new form pos */
    public poss() {
        initComponents();
        txtdiscount.setText("");
        txtname.setText("");
        txtprice.setText("");
        txtqty.setText("");
        txtsku.setText("");

        new Thread(new Runnable() {

            public void run() {
                //throw new UnsupportedOperationException("Not supported yet.");   // this should be deleted...!
                while (true) {
                    Date d = new Date();
                    //lbldate.setText(d.toString());
                    String date = d.toString();
                    String arr[] = date.split(" ");
                    String dd = arr[5] + " / " + arr[1] + " / " + arr[2];
                    lbldate.setText(dd);

                    lbltime.setText(arr[3]);
                }
            }
        }).start();

        double x = 0;
        x = Math.random() * 1000000;
        DecimalFormat d1 = new DecimalFormat("#");
        int y = Integer.parseInt(d1.format(x));
        String billno = "INV" + Integer.toString(y);
        lblbillno.setText(billno);
    }

    poss(String text) {
        //throw new UnsupportedOperationException("Not yet implemented");
        initComponents();
        txtdiscount.setText("");
        txtname.setText("");
        txtprice.setText("");
        txtqty.setText("");
        txtsku.setText("");

        new Thread(new Runnable() {

            public void run() {
                //throw new UnsupportedOperationException("Not supported yet.");   // this should be deleted...!
                while (true) {
                    Date d = new Date();
                    //lbldate.setText(d.toString());
                    String date = d.toString();
                    String arr[] = date.split(" ");
                    String dd = arr[5] + " / " + arr[1] + " / " + arr[2];
                    lbldate.setText(dd);

                    lbltime.setText(arr[3]);
                }
            }
        }).start();
        

        double x = 0;
        x = Math.random() * 1000000;
        DecimalFormat d1 = new DecimalFormat("#");
        int y = Integer.parseInt(d1.format(x));
        String billno = "INV" + Integer.toString(y);
        lblbillno.setText(billno);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtsku = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtprice = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtqty = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtdiscount = new javax.swing.JTextField();
        lblbillno = new javax.swing.JLabel();
        lbldate = new javax.swing.JLabel();
        lbltime = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        lblgrandtot = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblsubtot = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        btnbill = new javax.swing.JButton();
        btnhome = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtpara = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Bill #"); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 50, 20));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Time"); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 50, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Date"); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 50, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Product SKU"); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        txtsku.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtsku.setText("jTextField1"); // NOI18N
        txtsku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtskuActionPerformed(evt);
            }
        });
        getContentPane().add(txtsku, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 160, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Name"); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, -1, -1));

        txtname.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtname.setText("jTextField1"); // NOI18N
        getContentPane().add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 160, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Price"); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, -1, -1));

        txtprice.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtprice.setText("jTextField1"); // NOI18N
        getContentPane().add(txtprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 160, 130, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Qty"); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, -1, -1));

        txtqty.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtqty.setText("jTextField1"); // NOI18N
        txtqty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtqtyActionPerformed(evt);
            }
        });
        getContentPane().add(txtqty, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 160, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Discount"); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, -1, -1));

        txtdiscount.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtdiscount.setText("jTextField1"); // NOI18N
        txtdiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdiscountActionPerformed(evt);
            }
        });
        getContentPane().add(txtdiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 160, -1));

        lblbillno.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblbillno.setText("jLabel2"); // NOI18N
        getContentPane().add(lblbillno, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 140, 20));

        lbldate.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbldate.setText("jLabel2"); // NOI18N
        getContentPane().add(lbldate, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 140, -1));

        lbltime.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbltime.setText("jLabel2"); // NOI18N
        getContentPane().add(lbltime, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 90, -1));

        jTable1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product SKU", "Name", "Qty", "Price", "Discount"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 550, 210));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("PRINT BILL"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 360, 210, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel9.setText("BILLING SYSTEM"); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 24, 370, 50));

        lblgrandtot.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lblgrandtot.setText("00.00"); // NOI18N
        getContentPane().add(lblgrandtot, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 320, 170, -1));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel15.setText("Sub Total"); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 130, 30));

        lblsubtot.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lblsubtot.setText("00.00"); // NOI18N
        getContentPane().add(lblsubtot, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 290, 170, -1));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel17.setText("Grand Total"); // NOI18N
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, 150, 30));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("PRINT PARA BILL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 420, 200, 40));

        btnbill.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        btnbill.setText("Print Bill"); // NOI18N
        btnbill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbillActionPerformed(evt);
            }
        });
        getContentPane().add(btnbill, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 500, 180, 40));

        btnhome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnhome.setText("LOGOUT"); // NOI18N
        btnhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeActionPerformed(evt);
            }
        });
        getContentPane().add(btnhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 130, 20));

        jButton3.setText(" Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 130, 20));
        getContentPane().add(txtpara, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 470, 180, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/solid_colors_stains_light_18571_1920x1200.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -70, 1250, 710));

        setSize(new java.awt.Dimension(811, 579));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

private void txtskuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtskuActionPerformed
// TODO add your handling code here:
    try {
        Connection c = DB.mycon();
        Statement s = c.createStatement();
        ResultSet rs = s.executeQuery("SELECT * FROM product WHERE id='" + txtsku.getText() + "'");
        while (rs.next()) {
            txtname.setText(rs.getString("name"));
            txtprice.setText(rs.getString("price"));

        }
        txtqty.grabFocus();
    } catch (Exception e) {
        e.printStackTrace();
    }
}//GEN-LAST:event_txtskuActionPerformed

private void txtqtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtqtyActionPerformed
// TODO add your handling code here:
    txtdiscount.grabFocus();
}//GEN-LAST:event_txtqtyActionPerformed

private void txtdiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdiscountActionPerformed
// TODO add your handling code here:
    try {
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        Vector v = new Vector();
        v.add(txtsku.getText());
        v.add(txtname.getText());
        v.add(txtqty.getText());
        v.add(txtprice.getText());
        v.add(txtdiscount.getText());
        dtm.addRow(v);

        String price = txtprice.getText();
        String qty = txtqty.getText();
        String discount = txtdiscount.getText();

        double price1 = Double.parseDouble(price);
        double qty1 = Double.parseDouble(qty);
        double discount1 = Double.parseDouble(discount);

        subtot =  (price1 * qty1);
        DecimalFormat d1 = new DecimalFormat("#.00");
        lblsubtot.setText(d1.format(subtot));
        grandtot = grandtot + ((price1 * qty1) - discount1);
        lblgrandtot.setText(d1.format(grandtot));

        if (txtdiscount.getText() == null) {
            txtdiscount.setText("0");
            txtsku.grabFocus();
        } else {
            txtsku.grabFocus();
        }

        //save code gahanna
          Connection c = DB.mycon();
            Statement s = c.createStatement();
            s.executeUpdate("INSERT INTO pos (sku,name,price,qty,discount,subtot,grandtot,billno) VALUES  ('" + txtsku.getText() + "','" + txtname.getText() + "','" + txtprice.getText() + "','" + txtqty.getText() + "','" + txtdiscount.getText() + "','"+lblsubtot.getText()+"','"+lblgrandtot.getText()+"','"+lblbillno.getText()+"')");
        
        txtsku.setText("");
        txtdiscount.setText("0");
        txtprice.setText("");
        txtname.setText("");
        txtqty.setText("");



    } catch (Exception e) {
        e.printStackTrace();
    }
}//GEN-LAST:event_txtdiscountActionPerformed

private void btnhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeActionPerformed
// TODO add your handling code here:
   new loging().setVisible(true);
    this.dispose();
}//GEN-LAST:event_btnhomeActionPerformed

private void btnbillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbillActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_btnbillActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
     try {
        /* A sample calling */
        HashMap param = new HashMap();
//param.put("reportParameterName",valueForTheParameter);
        MyiReportViewer viewer = new MyiReportViewer("C:\\Users\\Rakshitha Kasun\\Desktop\\ST2PROJECT\\ireport\\newbill.jasper", param);
        viewer.setVisible(true);

    } catch (Exception e) {
        e.printStackTrace();
    }
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
     try {
        /* A sample calling */
        HashMap param = new HashMap();
param.put("cat",txtpara.getText());
        MyiReportViewer viewer = new MyiReportViewer("C:\\Users\\Rakshitha Kasun\\Desktop\\ST2PROJECT\\ireport\\billpara.jasper", param);
        viewer.setVisible(true);

    } catch (Exception e) {
        e.printStackTrace();
    }
    
    
}//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
        home h = new home();
        h.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                try {
                    UIManager.setLookAndFeel(new McWinLookAndFeel());
                    new poss().setVisible(true);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(poss.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbill;
    private javax.swing.JButton btnhome;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblbillno;
    private javax.swing.JLabel lbldate;
    private javax.swing.JLabel lblgrandtot;
    private javax.swing.JLabel lblsubtot;
    private javax.swing.JLabel lbltime;
    private javax.swing.JTextField txtdiscount;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtpara;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtqty;
    private javax.swing.JTextField txtsku;
    // End of variables declaration//GEN-END:variables
}
