/*
 * employee.java
 *
 * Created on April 23, 2017, 12:52 AM
 */
package ordermanagementsystem;

import com.jtattoo.plaf.AbstractLookAndFeel;
import com.jtattoo.plaf.acryl.AcrylLookAndFeel;
import com.jtattoo.plaf.aero.AeroLookAndFeel;
import com.jtattoo.plaf.aluminium.AluminiumLookAndFeel;
import com.jtattoo.plaf.bernstein.BernsteinLookAndFeel;
import com.jtattoo.plaf.graphite.GraphiteLookAndFeel;
import com.jtattoo.plaf.luna.LunaLookAndFeel;
import com.jtattoo.plaf.mcwin.McWinLookAndFeel;
import com.jtattoo.plaf.smart.SmartLookAndFeel;
import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.HashMap;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author  Rakshitha Kasun
 */
public class product extends javax.swing.JFrame {

    /** Creates new form employee */
    public product() {
        initComponents();
        txtid.setText("");
        txtname.setText("");
        txtprice.setText("");
        txtsup.setText("");
        txtmanu.setText("");
        txtexp.setText("");
        cmbtype.setSelectedIndex(0);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        txtprice = new javax.swing.JTextField();
        txtsup = new javax.swing.JTextField();
        txtmanu = new javax.swing.JTextField();
        txtexp = new javax.swing.JTextField();
        lblimg = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        cmbtype = new javax.swing.JComboBox();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(300, 300));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel2.setText("  TYPE");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 130, -1));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel3.setText("ID NUMBER");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 130, -1));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel4.setText("NAME");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 80, -1));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel5.setText("PRICE");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 80, -1));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel6.setText("SUPPLIER");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 130, -1));

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel8.setText("STOCK PLACE");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 170, -1));

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel9.setText("QUANTITY");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 140, -1));

        txtid.setText("jTextField1");
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 200, -1));

        txtname.setText("jTextField1");
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        getContentPane().add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 200, -1));

        txtprice.setText("jTextField1");
        txtprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpriceActionPerformed(evt);
            }
        });
        getContentPane().add(txtprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 200, -1));

        txtsup.setText("jTextField1");
        txtsup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsupActionPerformed(evt);
            }
        });
        getContentPane().add(txtsup, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 200, -1));

        txtmanu.setText("jTextField1");
        txtmanu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmanuActionPerformed(evt);
            }
        });
        getContentPane().add(txtmanu, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 200, -1));

        txtexp.setText("jTextField1");
        getContentPane().add(txtexp, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 200, -1));

        lblimg.setBorder(javax.swing.BorderFactory.createTitledBorder("IMAGE"));
        getContentPane().add(lblimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 280, 180));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("UPLOAD IMAGE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, 170, 30));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("DELETE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 383, 130, 30));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("SAVE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 383, 130, 30));

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton6.setText("LOGOUT");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, 120, 20));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("SEARCH");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 383, 130, 30));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton5.setText("UPDATE");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 383, 130, 30));

        jButton7.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jButton7.setText("GENERATE FULL REPORT");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 430, 210, -1));

        cmbtype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select type", "cloths", "shoes", "toys", "electrical items", "grossery items" }));
        getContentPane().add(cmbtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 200, -1));

        jButton8.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jButton8.setText("GENERATE PRODUCT REPORT");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 470, 210, -1));

        jButton9.setText("Back");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 130, 20));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel7.setText("PRODUCT DETAILS");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 650, 30));

        jLabel1.setFont(new java.awt.Font("Bodoni MT Condensed", 1, 48)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Plain Twitter Backgrounds - Free Twitter Layouts w Color Codes.jpg"))); // NOI18N
        jLabel1.setText("                         EMPLOYEE DETAILS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 550));

        setSize(new java.awt.Dimension(810, 587));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:

    int x = JOptionPane.showConfirmDialog(rootPane, "Do you want to Delete?");
    if (x == 0) {
        try {
            Connection c = DB.mycon();
            Statement s = c.createStatement();
            s.executeUpdate("DELETE from product WHERE id='" + txtid.getText() + "'");
            txtid.setText("");
            txtname.setText("");
            txtprice.setText("");
            txtsup.setText("");
            txtmanu.setText("");
            txtexp.setText("");
            cmbtype.setSelectedIndex(0);
            lblimg.setIcon(null);

            JOptionPane.showMessageDialog(rootPane, "Deleted Succesfuly");

        } catch (Exception e) {
            e.printStackTrace();
        }
    } else if (x == 1) {
        txtid.setText("");
        txtname.setText("");
        txtprice.setText("");
        txtsup.setText("");
        txtmanu.setText("");
        txtexp.setText("");
        cmbtype.setSelectedIndex(0);
        lblimg.setIcon(null);
    }

}//GEN-LAST:event_jButton2ActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
// TODO add your handling code here:

    try {

        int x = JOptionPane.showConfirmDialog(rootPane, "Do you want to save?");
        if (x == 0) {
            //jFileChooser1.showOpenDialog(this);
            File f = jFileChooser1.getSelectedFile();
            String path = f.getAbsolutePath();
            path = path.replace("\\", "/");




            Connection c = DB.mycon();
            Statement s = c.createStatement();
            s.executeUpdate("INSERT INTO product VALUES('" + txtid.getText() + "','" + txtname.getText() + "','" + txtprice.getText() + "','" + txtsup.getText() + "','" + txtmanu.getText() + "','" + txtexp.getText() + "','" + cmbtype.getSelectedItem().toString() + "','" + path + "')");

            txtid.setText("");
            txtname.setText("");
            txtprice.setText("");
            txtsup.setText("");
            txtmanu.setText("");
            txtexp.setText("");
            cmbtype.setSelectedIndex(0);
            lblimg.setIcon(null);

            JOptionPane.showMessageDialog(rootPane, "Succesfuly Saved");
        } else if (x == 1) {
            txtid.setText("");
            txtname.setText("");
            txtprice.setText("");
            txtsup.setText("");
            txtmanu.setText("");
            txtexp.setText("");
            cmbtype.setSelectedIndex(0);
             lblimg.setIcon(null);
        }

    } catch (Exception e) {

        e.printStackTrace();

    }
}//GEN-LAST:event_jButton3ActionPerformed

private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
// TODO add your handling code here:
    new loging().setVisible(true);
    this.dispose();
}//GEN-LAST:event_jButton6ActionPerformed

private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
// TODO add your handling code here:
    try {
        Connection c = DB.mycon();
        Statement s = c.createStatement();
        ResultSet rs = s.executeQuery("SELECT * FROM product WHERE id='" + txtid.getText() + "'");
        while (rs.next()) {
            txtname.setText(rs.getString("name"));
            txtprice.setText(rs.getString("price"));
            txtsup.setText(rs.getString("supplier"));
            txtmanu.setText(rs.getString("quantity"));
            txtexp.setText(rs.getString("store"));
            cmbtype.setSelectedItem(rs.getString("type"));

            File f1 = new File(rs.getString("image"));

            Image im = ImageIO.read(f1);
            im = im.getScaledInstance(lblimg.getWidth(), lblimg.getHeight(), Image.SCALE_SMOOTH);
            lblimg.setIcon(new ImageIcon(im));
        }

    } catch (Exception e) {
        e.printStackTrace();
    }
}//GEN-LAST:event_jButton4ActionPerformed

private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
// TODO add your handling code here:
   try {
        int x = JOptionPane.showConfirmDialog(rootPane, "Do you want to Update ?");
        if (x == 0) {
            
            
            
            
            Connection c = DB.mycon();
            Statement s = c.createStatement();
            s.executeUpdate("UPDATE product SET name='" + txtname.getText() + "',price='" + txtprice.getText() + "',supplier='" + txtsup.getText() + "',quantity='" + txtmanu.getText() + "',store='"+txtexp.getText()+"',type='" + cmbtype.getSelectedItem().toString() + "' WHERE id='" + txtid.getText() + "'");

            txtid.setText("");
            txtname.setText("");
            txtprice.setText("");
            txtsup.setText("");
            txtmanu.setText("");
            txtexp.setText("");
            cmbtype.setSelectedIndex(0);
             lblimg.setIcon(null);
            JOptionPane.showMessageDialog(rootPane, "Succesfuly Updated");
        } else if (x == 1) {
            txtid.setText("");
            txtname.setText("");
            txtprice.setText("");
            txtsup.setText("");
            txtmanu.setText("");
            txtexp.setText("");
            cmbtype.setSelectedIndex(0);
             lblimg.setIcon(null);
        }

    } catch (Exception e) {
        e.printStackTrace();
    }
}//GEN-LAST:event_jButton5ActionPerformed

private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
// TODO add your handling code here:
    txtname.grabFocus();
}//GEN-LAST:event_txtidActionPerformed

private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
// TODO add your handling code here:
    txtprice.grabFocus();
}//GEN-LAST:event_txtnameActionPerformed

private void txtpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpriceActionPerformed
// TODO add your handling code here:
    txtsup.grabFocus();
}//GEN-LAST:event_txtpriceActionPerformed

private void txtsupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsupActionPerformed
// TODO add your handling code here:
    txtmanu.grabFocus();
}//GEN-LAST:event_txtsupActionPerformed

private void txtmanuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmanuActionPerformed
// TODO add your handling code here:
    txtexp.grabFocus();
}//GEN-LAST:event_txtmanuActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    try {
        jFileChooser1.showOpenDialog(this);
        File f = jFileChooser1.getSelectedFile();
        String path = f.getAbsolutePath();
        path = path.replace("\\", "/");
        File f1 = new File(path);

        Image im = ImageIO.read(f1);
        im = im.getScaledInstance(lblimg.getWidth(), lblimg.getHeight(), Image.SCALE_SMOOTH);
        lblimg.setIcon(new ImageIcon(im));






    } catch (Exception e) {
        e.printStackTrace();
    }


}//GEN-LAST:event_jButton1ActionPerformed

private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
// TODO add your handling code here:
    try {
        /* A sample calling */
        HashMap param = new HashMap();
//param.put("reportParameterName",valueForTheParameter);
        MyiReportViewer viewer = new MyiReportViewer("C:\\Users\\Rakshitha Kasun\\Desktop\\ST2PROJECT\\ireport\\productgood.jasper", param);
        viewer.setVisible(true);

    } catch (Exception e) {
        e.printStackTrace();
    }
}//GEN-LAST:event_jButton7ActionPerformed

private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
// TODO add your handling code here:
    try {
        /* A sample calling */
        HashMap param = new HashMap();
        param.put("cat", txtid.getText());
        MyiReportViewer viewer = new MyiReportViewer("C:\\Users\\Rakshitha Kasun\\Desktop\\ST2PROJECT\\ireport\\productgoodpara.jasper", param);
        viewer.setVisible(true);

    } catch (Exception e) {
        e.printStackTrace();
    }

}//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
                this.dispose();
                home h = new home();
                h.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                try {
                    UIManager.setLookAndFeel(new McWinLookAndFeel());

                } catch (Exception e) {
                    e.printStackTrace();
                }
                new product().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbtype;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblimg;
    private javax.swing.JTextField txtexp;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtmanu;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtsup;
    // End of variables declaration//GEN-END:variables
}
